### ISSUE TITLE
Fix that navbar absolute.

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#2]

**Comment by Anu27n** [comment]
Assigned all the best 👍

**Comment by abhayksahu369** [comment]
can you please add gssoc-ext label also

**Comment by Anu27n** [comment]
done

**Comment by abhayksahu369** [comment]
@Anu27n  brother this contribution is still not showing in my gssoc profile 😅 ,I think you need to add level label also ....like level1 ,level2 , level3
